name: CI

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: brew install swiftlint swiftgen bartycrouch

    - name: Run tests
      run: xcodebuild test -project Clipy.xcodeproj -scheme Clipy -verbose -clean
