name: Danger

on: pull_request

jobs:
  swiftlint:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SwiftLint
      run: |
        brew install swiftlint
        swiftlint lint --reporter github-actions-logging
